# Generated by Django 3.2.4 on 2021-07-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='descricao',
            new_name='descrição',
        ),
    ]
