# Generated by Django 3.2.4 on 2021-07-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0003_rename_descrição_tarefas_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='titulo',
            field=models.CharField(max_length=110),
        ),
    ]
